rteannotator/rte/views.py
# -*- coding: utf-8 -*-

import os
import json
import flask
import werkzeug
from flask import session, request, Blueprint
from flask_login import login_required, login_user, logout_user, current_user
from flask_babel import gettext
from flask_breadcrumbs import register_breadcrumb
from sqlalchemy import update

from model import *
from rteannotator import model
from rteannotator import utils
from rteannotator import app
from rteannotator import db
from rteannotator import babel
from config import LANGUAGES

bp = Blueprint('rte', __name__, url_prefix='/rte')

ITEMS_PER_PAGE = 5

@bp.route('/')
@register_breadcrumb(bp, '.', 'RTE')
@login_required
def index():
    return flask.render_template('rte-index.html')

@bp.route('/choose-file', methods=['GET', 'POST'])
@login_required
def choose_file():
    filename = request.form['filename']
    if not utils.check_filename(filename):
        return flask.render_template('forbidden.html')

    session['filename'] = filename
    return flask.redirect(flask.url_for('display_rte_data'))

@bp.route('/review-file/', defaults={'page': None, 'file_id': None})
@bp.route('/review-file/<int:file_id>/', defaults={'page': 1})
@bp.route('/review-file/<int:file_id>/<int:page>')
@login_required
def review_file(file_id, page=1):
    '''
    Display previously annotated pairs.
    '''
    if file_id is None:
        return ''

    rte_file = model.File.query.get(file_id)
    rte_file.load_metadata()
    pair_query = get_pairs_file_query(file_id, True)
    pair_annotated_by_user_query = filter_annotations_by_user(pair_query)
    num_pairs = pair_annotated_by_user_query.count()
    paginated_query = utils.paginate_query(pair_query, page, ITEMS_PER_PAGE)
    num_pages = utils.find_num_pages(num_pairs, ITEMS_PER_PAGE)

    pairs = paginated_query.all()
    add_annotations_by_user(pairs)
    return flask.render_template('view-rte.html',
                                 page=page,
                                 file=rte_file,
                                 pairs=pairs,
                                 num_pages=num_pages,
                                 annotations_per_pair=DESIRED_ANNOTATIONS_PER_PAIR,
                                 showing_all=current_user.show_all_pairs)

@bp.route('/annotate-file/', defaults={'page': None, 'file_id': None})
@bp.route('/annotate-file/<int:file_id>', defaults={'page': 1})
@bp.route('/annotate-file/<int:file_id>/<int:page>')
@login_required
def annotate_file(file_id, page):
    '''
    Display an RTE file for annotation.
    '''
    rte_file = model.File.query.get(file_id)
    rte_file.load_metadata()

    # get ITEMS_PER_PAGE pairs for this annotator
    pairs = get_pairs_for_annotation(file_id, ITEMS_PER_PAGE)

    add_annotations_by_user(pairs)

    return flask.render_template('view-rte.html',
                                 page=page,
                                 file=rte_file,
                                 pairs=pairs,
                                 annotations_per_pair=DESIRED_ANNOTATIONS_PER_PAIR,
                                 showing_all=current_user.show_all_pairs)

@bp.route('/examples')
def examples():
    '''
    Show annotation examples
    '''
    return flask.render_template('examples.html')

# @bp.route('/combine-files', methods=['GET', 'POST'])
# @login_required
# def combine_files():
#     '''
#     Combine the annotated data in the given files, providing a single
#     one to download.
#     '''
#     if request.method == 'GET':
#         return flask.render_template('choose-file.html',
#                                      filenames=utils.get_uploaded_files(),
#                                      action_url=flask.url_for('combine_files'),
#                                      multiselect=True)
#
#     filenames = request.form.getlist('filenames[]')
#     all_pairs = []
#     for filename in filenames:
#         if not utils.check_filename(filename):
#             return flask.render_template('forbidden.html')
#
#         full_path = os.path.join(utils.get_upload_folder(), filename)
#         file_data = utils.load_pairs_from_xml(full_path)
#         pairs = file_data.pairs
#         annotated_pairs = [pairs[num] for num in pairs
#                            if pairs[num].entailment != 'UNKNOWN']
#         all_pairs.extend(annotated_pairs)
#
# #     file_data = model.FileData(None, all_pairs, len(all_pairs))
#
#     tree = file_data.generate_xml()
#     combined_file = 'combined-rte.xml'
#     path = os.path.join(utils.get_upload_folder(), combined_file)
#     tree.write(path, 'utf-8', True)
#
#     return flask.send_file(path, as_attachment=True,
#                            mimetype='text/plain')


@bp.route('/statistics/', defaults={'file_id': None})
@bp.route('/statistics/<int:file_id>')
@login_required
def statistics(file_id):
    file_ = model.File.query.get(file_id)

    stats = compute_file_statistics(file_id)
    metrics, entailment_counter, similarity_counter = stats

    return flask.render_template('statistics.html',
                                 filename=file_.name,
                                 entailment_counter=entailment_counter,
                                 similarity_counter=similarity_counter,
                                 metrics=metrics)

@bp.route('/annotator-statistics', methods=['POST'])
@login_required
def annotator_statistics():
    '''
    Return a view with statistics on annotators's raw agreement.
    '''
    ids_string = request.form['ids']
    annotator_ids = [int(val) for val in json.loads(ids_string)]
    annotator_ids.sort()

    agreements = compute_annotators_statistics(annotator_ids)
    annotators = get_annotators(annotator_ids)
    for annotator, agreement in zip(annotators, agreements):
        annotator.agreement = agreement

    return flask.render_template('annotator-statistics.html', users=annotators)

@bp.route('/overall-statistics', methods=['GET', 'POST'])
@login_required
def overall_statistics():
    '''
    Return a view with statistics over all pair annotations.
    '''
    if request.method == 'POST':
        # annotator ids were sent via post
        ids_string = request.form['ids']
        annotator_ids = json.loads(ids_string)
    else:
        annotator_ids = None

    try:
        stats = compute_overall_statistics(annotator_ids)
    except IndexError:
        if annotator_ids is not None:
            flask.flash(gettext('No pairs fully annotated by only the selected annotators.'), 'error')
            return flask.redirect(flask.url_for('view_users'))
        else:
            flask.flash(gettext('No pairs fully annotated.'), 'error')
            return flask.redirect(flask.url_for('rte.view_files'))

    metrics, entailment_counter, similarity_counter = stats

    return flask.render_template('statistics.html',
                                 entailment_counter=entailment_counter,
                                 similarity_counter=similarity_counter,
                                 metrics=metrics)

@bp.route('/annotate-pair')
@bp.route('/annotate-pair/<annotation_type>/<pair_id>/<class_>')
@login_required
def annotate_pair(annotation_type=None, pair_id=None, class_=None):
    '''
    Receive entailment or similarity annotation.
    '''
    if pair_id is None:
        # Ugly hack just to provide an endpoint with no arguments
        return ''

    annotator_id = current_user.id
    annotate_pair_rte(annotation_type, pair_id, annotator_id, class_)

    response_data = {'ok': True}
    return json.dumps(response_data)

@bp.route('/hints')
def hints():
    return flask.render_template('hints.html')

@bp.route('/download/', defaults={'file_id': None})
@bp.route('/download/<int:file_id>')
@login_required
def download_raw(file_id):
    if file_id is None:
        return ''

    file_ = model.File.query.get(file_id)
    file_data = generate_rte_file(file_id)
    return flask.send_file(file_data, as_attachment=True,
                           mimetype='text/xml',
                           attachment_filename=file_.name)

@bp.route('/view-files')
@login_required
def view_files():
    '''
    Just show the available files and operations on them.
    '''
    File = model.File
    files = File.query.filter_by(available=True, type='rte').all()
    for file_ in files:
        file_.load_metadata()

    return flask.render_template('choose-file.html', files=files)

@bp.route('/get-pair/<int:file_id>')
@login_required
def get_pair_for_review(file_id):
    '''
    Get a pair from the specified file to be reviewed by a user
    '''
    username = session['username']
    pair = get_unreviewed_pair(username, file_id)
    if pair is None:
        response_data = {'empty': True}
    else:
        response_data = {'id': pair.id,
                         't': pair.t,
                         'h': pair.h}

    response_data['ok'] = True
    return json.dumps(response_data)

@bp.route('/clean-file/', defaults={'file_id': None})
@bp.route('/clean-file/<int:file_id>')
@login_required
def clean_file(file_id):
    if file_id is None:
        return ''

    return flask.render_template('clean.html',
                                 file_id=file_id)

@bp.route('/clean-pair', methods=['POST'])
@login_required
def clean_pair():
    '''
    Make a change in a pair.
    '''
    if not current_user.may_edit_pair():
        return json.dumps({'ok': False})

    annotator_name = current_user.name
    operation = request.form['operation']
    pair_id = request.form['pair_id']

    if operation == 'delete':
        delete_pair(annotator_name, pair_id)
    elif operation == 'change':
        t = request.form['t']
        h = request.form['h']
        change_pair(pair_id, t, h, True)
    else:
        mark_as_reviewed(annotator_name, pair_id)

    return json.dumps({'ok': True})

@bp.route('/edit-pair', methods=['POST'])
@login_required
def edit_pair():
    '''Edit an existing pair, which was supposedly ready.'''
    if not current_user.may_edit_pair():

rteannotator/templates/annotator-statistics.html
{% extends "layout-rte.html" %}

{% block link %}
<link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}" />
{% endblock %}

{% block script %}
<script type="text/javascript" src="{{ url_for('static', filename='jquery-2.1.4.min.js') }}"></script>
{% endblock %}

{% block content %}
    <table id="usertable">
        <thead>
            <tr>
                <th>Annotator name</th>
                <th>Mean agreement</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr class="username-item filename-item">
                    <td>{{ user.name }}</td>
                    <td>{{ "{:.2%}".format(user.agreement) }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

rteannotator/templates/choose-file.html
{% extends "layout-rte.html" %}

{% block link %}
<link rel="stylesheet" href="{{ url_for('static', filename='choose-file.css') }}" />
{% endblock %}

{% block script %}
<script type="text/javascript" src="{{ url_for('static', filename='utils.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='jquery-2.1.4.min.js') }}"></script>
<script>
    var selectedFile = '';
    
    $(function(){
        $('.filename-item').click(function(){
            selectedFile = $(this).attr('data-file-id');
            // remove previously selected element
            $('.selected').removeClass('selected');
            $(this).addClass('selected');
        });
    });

    $(function(){
        $('.command-button').click(function(){
            if (selectedFile == '') {
                return;
            }
            
            url = this.getAttribute('data-link') + selectedFile;
            location.href = url;
        });
    });
    
    $(function(){
        $('#overall-stats').click(function(){
            url = this.getAttribute('data-link');
            location.href = url;
        });
    });
    
{% if current_user.may_download_annotated_file() %}
    $(function(){
        $('#download-annotated').click(function(){
            if (selectedFile == '') {
                return;
            }
            
            hiddenInput = $('#file-id');
            hiddenInput.val(selectedFile);
            
            //alert(hiddenInput.val());
            $('.download-panel form').submit();
        });
    });
{% endif %}
</script>
{% endblock %}

{% block content %}
<div class="filenames">
    <table id="filetable">
        <thead>
            <tr>
                <th>Filename</th>
                <th>Total pairs</th>
                <th>Ready for annotation</th>
                <th>Pairs you reviewed</th>
                <th>Annotations</th>
                <th>Pairs you annotated</th>
                <th>Pairs with enough annotations</th>
            </tr>
        </thead>
        
        <tbody>
        {% for file_ in files %}
            <tr class="filename-item selectable" id="{{ file_.name }}" data-file-id="{{ file_.id }}">
                <td class="button">{{ file_.name }}</td>
                <td class="number">{{ file_.pairs.count() }}</td>
                <td class="number">{{ file_.num_reviewed_and_kept }}</td>
                <td class="number">{{ file_.num_reviewed_by_user }}</td>
                <td class="number">{{ file_.num_annotations }}</td>
                <td class="number">{{ file_.num_annotated_by_user }}</td>
                <td class="number">{{ file_.num_annotated_enough }}</td>
            </tr>
        {% endfor %}
        </tbody>
        
    </table>
    
    <div class="control-buttons">
        {% if current_user.may_edit_pair() %}
            <button class="command-button link-button" data-link="{{ url_for('rte.clean_file') }}">Clean</button>
        {% endif %}
        <button class="command-button link-button" data-link="{{ url_for('rte.annotate_file') }}">Annotate</button>
        {% if current_user.may_download_raw_file() %}
            <button class="command-button link-button" data-link="{{ url_for('download_raw') }}">Download</button>
        {% endif %}
        <button class="command-button link-button" data-link="{{ url_for('rte.statistics') }}">Statistics</button>
        <button class="link-button" id="overall-stats" data-link="{{ url_for('rte.overall_statistics') }}">Overall Statistics</button>
        
        {% if current_user.may_download_annotated_file() %}
            <div class="download-panel">
                <form action="{{ url_for('download_annotated') }}" method="post">
                    <label for="num-pairs">Number of pairs:</label>
                    <input type="number" id="num-pairs" name="num-pairs" min="1"/>
                    
                    <label for="agreeing">Agreeing annotations:</label>
                    <input type="number" id="agreeing" name="agreeing" min="1"/>
                    
                    <label for="all-files">All files</label>
                    <input type="checkbox" id="all-files" name="all-files"/>
                    
                    <input type="hidden" id="file-id" name="file-id"/>
                    
                    <button class="link-button" id="download-annotated">Download Annotated</button>
                </form>
            </div>
        {% endif %}
        
    </div>
</div>
{% endblock %}

rteannotator/templates/comptext-analytics.html
{% extends "layout-comptext.html" %}

{% block link %}
<link rel="stylesheet" href="{{ url_for('static', filename='comptext-analytics.css') }}" />
{% endblock %}

{% from "table.html" import table, icc_table, confusion_table, num_annotations_table %}

{% block content %}
	<h1>Estatísticas</h1>
	{% set fully_annotated_num = fully_annotated|length %}
	{% if fully_annotated_num > 0 %}
		<b>Total de anotações:</b> {{ num_annotations["total"] }} / {{ expected_num_annotations }}<br>
		<b>Número de pares com {{ DESIRED_ANNOTATIONS_PER_PAIR }} anotações:</b> {{ fully_annotated_num }} / {{ expected_num_annotated_pairs }}<br>
		{% if texts_not_in_fully_annotated %}
			<b>Textos não presentes nos {{ fully_annotated_num }} pares com {{ DESIRED_ANNOTATIONS_PER_PAIR }} anotações:</b>
			{% for t in texts_not_in_fully_annotated %}
				{% if loop.index0 %}, {% endif %}<a href="{{ url_for("comptext.view_texts", page=0, text_id=t.id) }}">{{ t.title }}</a>
			{% endfor %}
			<br>
		{% endif %}
		<b>Número de pares com anotação majoritária (3 ou {{ DESIRED_ANNOTATIONS_PER_PAIR }} anotações concordantes):</b> {{ num_majoritary_voted }} / {{ fully_annotated_num }}<br>
		<br>

		<div class="container">
			<div class="column">
				<b>Kappa de Fleiss entre anotadores e linguistas (utilizando somente os {{ fully_annotated_num }} pares com {{ DESIRED_ANNOTATIONS_PER_PAIR }} anotações):</b> {{ "%.2g"|format(kappa4all) }}<br>
				<br>
				<b>Kappa de Fleiss entre os anotadores (utilizando somente os {{ fully_annotated_num }} pares com {{ DESIRED_ANNOTATIONS_PER_PAIR }} anotações):</b> {{ "%.2g"|format(kappa4teachers) }}<br>
				<br>
				Como interpretar o Kappa:
				{{ table(["Valor de Kappa", "Interpretação"],
						 [["Entre 0 e 0.4", "Pobre"],
						  ["Entre 0.4 e 0.75", "Bom"],
						  ["Entre 0.75 e 1", "Excelente"]])
				}}
				<br>

				<b>Anotações por professor</b>
				{{ num_annotations_table([ _("Annotator"), _("Number of annotations"), _("Number of comments") ], num_annotations["table"], real_name) }}
				<br>
			</div>
			<div class="column">
				Legenda dos valores de anotação:
				{{ table(["Valor", "Abreviação", "Significado"],
						 [["1", "E >> D", value_labels[0]],
						  ["2", "E > D", value_labels[1]],
						  ["3", "E = D", value_labels[2]],
						  ["4", "D > E", value_labels[3]],
						  ["5", "D >> E", value_labels[4]]])
				}}

				<b>Matriz de confusão das {{ num_majoritary_voted }} anotações majoritárias:</b>
				{{ confusion_table(confusion_matrix, labels=["1. E >> D", "2. E > D", "3. E = D", "4. D > E", "5. D >> E", "Total"]) }}
				<br>

				<b>Matriz de confusão normalizada das {{ num_majoritary_voted }} anotações majoritárias (em porcentagem):</b>
				{{ confusion_table(normalized_confusion, labels=["1. E >> D", "2. E > D", "3. E = D", "4. D > E", "5. D >> E", "Total"]) }}
				<br>

				<b>Coeficiente de Correlação Intraclasse {{ icc["icc.name"] }} entre professores e linguista</b><br>
				(Modelo = "{{ icc["model"] }}", Tipo = "{{ icc["type"] }}", Unidade = "{{ icc["unit"] }}")<br>
				{{ icc_table(icc) }}
				<br>
				<b>Coeficiente de Correlação Intraclasse Agregando os extremos (1 e 2, 4 e 5) {{ icc_aggregated["icc.name"] }} entre professores e linguista</b><br>
				(Modelo = "{{ icc_aggregated["model"] }}", Tipo = "{{ icc_aggregated["type"] }}", Unidade = "{{ icc_aggregated["unit"] }}")<br>
				{{ icc_table(icc_aggregated) }}
				<b>Coeficiente de Correlação Intraclasse {{ icc_classifier["icc.name"] }} entre professores e classificador</b><br>
				(Modelo = "{{ icc_classifier["model"] }}", Tipo = "{{ icc_classifier["type"] }}", Unidade = "{{ icc_classifier["unit"] }}")<br>
				{{ icc_table(icc_classifier) }}
				<br>
				<b>Coeficiente de Correlação Intraclasse {{ icc4all["icc.name"] }} entre professores para todos os {{ expected_num_annotated_pairs }} pares</b><br>
				(Modelo = "{{ icc4all["model"] }}", Tipo = "{{ icc4all["type"] }}", Unidade = "{{ icc4all["unit"] }}")<br>
				{{ icc_table(icc4all) }}
				<br>

				Como interpretar o Coeficiente de Correlação Intraclasse:
				{{ table(["Valor do CCI", "Interpretação"],
						 [["Menor que 0.40", "Pobre"],
						  ["Entre 0.40 e 0.59", "Razoável"],
						  ["Entre 0.60 e 0.74", "Bom"],
						  ["Entre 0.75 e 1", "Excelente"]])
				}}
				<br>
			</div>
		</div>
		<img src="{{ url_for("static", filename="percent-agreement.png") }}" />
	{% else %}
		Não há pares com anotações suficientes ({{ DESIRED_ANNOTATIONS_PER_PAIR }})
	{% endif %}
{% endblock %}

rteannotator/templates/comptext-annotate-view.html
<div class="contaiter">
	<div class="column">
		<h3>{{ _('Text') }} 1</h3>
		<div class="text">
			{% autoescape false %}
				{{ pair.text1|htmlify }}
			{% endautoescape %}
		</div>
	</div>
	<div class="column">
		<h3>{{ _('Text') }} 2</h3>
		<div class="text">
			{% autoescape false %}
				{{ pair.text2|htmlify }}
			{% endautoescape %}
		</div>
	</div>
</div>

<form action="{{ url_for('comptext.submit_annotation') }}?pair={{ pair.id }}" method="post">
	<div class="eq-radio">
		<div class="caption">
			<h3><b>{{ _('Text') }} 1</b></h3>
		</div>
		{% for d in difficulties %}
		<div class="annotation-option">
			<input type="radio" required name="complexity" value="{{ loop.index }}" onChange="on_check('{{ d }}')" />
		</div>
		{% endfor %}
		<div class="caption">
			<h3><b>{{ _('Text') }} 2</b></h3>
		</div>

	</div>

	<br />
	<div id="caption-for-chosen">
		<i>{{ _('Choose which text is more complex') }}</i>
	</div>
	<br />

	<textarea name="comment" rows="2" placeholder="{{ _('Optional comment for your annotation') }}"></textarea>
	<br />
	<br />
	<div class="submit"><button class="submit" type="submit">{{ _('Submit') }}</button></div>
</form>

rteannotator/templates/comptext-annotate.html
{% extends "layout-comptext.html" %}

{% block link %}
<link rel="stylesheet" href="{{ url_for('static', filename='comptext.css') }}" />
<link rel="stylesheet" href="{{ url_for('static', filename='comptext-annotate.css') }}" />
{% endblock %}

{% block script %}
<script type="text/javascript" src="{{ url_for('static', filename='jquery-2.1.4.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='comptext-annotate.js') }}"></script>
{% endblock %}

{% block content %}
{% include "comptext-annotate-view.html" %}
{% endblock %}

rteannotator/templates/forbidden.html
{% extends "layout-rte.html" %}

{% block content %}
    <h1>Forbidden</h1>
    <p>You are trying to do Bad Things&trade;.</p>
{% endblock %}

rteannotator/templates/home.html
{% extends "layout.html" %}

{% block link %}
<link rel="stylesheet" href="{{ url_for('static', filename='comptext.css') }}" />
<link rel="stylesheet" href="{{ url_for('static', filename='home.css') }}" />
{% endblock %}

{% block content %}
	{% include "who-am-i.html" %}

	{% if current_user %}
	<ul id="main-menu">
		<div class="subsystems-table">
{#
			<div class="subsystem">
				<div class="text">
					<h2><a href="{{ url_for('rte.index') }}">RTE</a></h2>
Inferência Textual e Similaridade Semântica
são duas tarefas do processamento de línguas naturais
que tratam de pares de trechos de textos.
O objetivo da primeira é determinar se o significado
de um trecho implica o outro, enquanto que a segunda
atribui uma pontuação de similaridade semântica ao par.
				</div>
			</div>
#}
			<div class="subsystem">
				<div class="text">
					<h2><a href="{{ url_for('comptext.index') }}">Complexidade Textual</a></h2>
Avaliação da Complexidade Textual via comparação de pares
de textos é mais natural do que indicar um valor absoluto ou uma classe de
complexidade para um dado texto. Essa tarefa está adaptada para avaliar
textos de 4 bandas: 3o ano, 4-5o anos, 6-7o anos e 8-9o anos.
				</div>
			</div>
		</div>
		<!-- Other links -->
		<a class="main-menu" href="{{ url_for('change_password') }}">{{ _('Change password') }}</a>
		<br />
		<a class="main-menu" href="{{ url_for('my_annotations') }}">{{ _('My annotations') }}</a>
	</ul>

	{% if current_user.have_special_permissions() %}
		<h4>{{ _('Special permissions') }}</h4>
	{% endif %}
	{% if current_user.may_see_all_statistics() %}
		<a href="{{ url_for('view_users') }}">{{ _('View annotators') }}</a>
		<br />
	{% endif %}
	{% if current_user.is_admin() %}
		<a href="{{ url_for('admin.index') }}">Admin</a><br />
	{% endif %}
		{% if current_user.may_submit_file() %}
			<form action="{{ url_for('submit') }}" method="post" enctype="multipart/form-data">
				<fieldset id="submit-xml">
					<label for="file">{{ _('Submit XML file') }}</label>
					<input name="file" type="file" id="file"/>
					<br />
					<input type="submit" value="{{ _('Submit') }}" />
				</fieldset>
			</form>
		{% endif %}
	{% else %}

	<p>{{ _('You are not logged in') }}. <a href="{{ url_for('login') }}">{{ _('Click here to log in') }}</a>.</p>

	{% endif %}
{% endblock %}

rteannotator/templates/layout.html
<!doctype html>
<html>
    <head>
        {% block head %}
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        {% block link %}{% endblock %}
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>{% block title %}NILC Annotator{% endblock %}</title>
        {% block script %}{% endblock %}
        {% endblock %}
    </head>

    <body>
        <div id="wrapper">
            <div id="header">
                {% block header %}
					<div class="title">
						{%- for breadcrumb in breadcrumbs -%}
							<a href="{{ breadcrumb.url }}">{{ breadcrumb.text }}</a>
							{{ '/' if not loop.last }}
						{% endfor %}
					</div><br />
					{% if session['username'] %}
						<div class="user-info">{{ _('Logged in as') }} {{ session['username'] }} | <a href="{{ url_for('logout') }}">{{ _('Log out') }}</a></div>
					{% endif %}
                {% endblock %}
            </div>
            
            <div id="content">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        <ul class="flashes">
                            {% for category, message in messages %}
                                <li class="flash {{ category }}">{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div> 
            
            <div id="footer">
                {% block footer %}{% endblock %}
				<p class="developer">{{ _('Developed by') }} {% block developer %}Gil Barbosa Reis - NILC/USP{% endblock %}</p>
				<p class="contact">
					<i class="fa fa-envelope"></i>
					{{ _('Contact') }}:
					<a href="mailto:guten.aval@gmail.com">guten.aval@gmail.com</a>
				</p>
            </div>
        </div>
    </body>
</html>

rteannotator/templates/my-annotations.html
{% extends "layout.html" %}

{% block content %}
<h1>{{ _('My annotations') }}</h1>
{#
<h3>RTE</h3>
{% for A in rte %}
{% endfor %}

<hr />
#}

<h3>Complexidade Textual</h3>
{{ _("Total") }}: {{ comptext|length }}
<table>
	<tr>
		<th>{{ _("Text") }} 1</th>
		<th>{{ _("Text") }} 2</th>
	</tr>
{% for A in comptext %}
	<tr class="data">
		<td>{{ A.pair.text1.title }}</td>
		<td>{{ A.pair.text2.title }}</td>
	</tr>
{% endfor %}
</table>

{% endblock %}

rteannotator/templates/no-more-comptexts.html
{% extends "layout-comptext.html" %}

{% block content %}
<p>{{ _("There are no more pairs to annotate") }}.</p>
<h3>{{ _("Thank you very much for your contribution") }}!</h3>
{% endblock %}

rteannotator/templates/view-comptexts.html
{% extends "layout-comptext.html" %}

{% block link %}
<link rel="stylesheet" href="{{ url_for("static", filename="next-page.css") }}" />
{% endblock %}

{% block content %}
{% for T in texts %}
	<a href="{{ url_for("comptext.view_texts", page=page, text_id=T.id) }}">{{ T.title }}</a>
	<br />
{% endfor %}
<a id="next" href="{{ url_for("comptext.view_texts", page=page + 1) }}">{{ _("Next page") }}</a>
{% endblock %}